### ISSUE TITLE
Ocelot make Framesoc crash: "Color configuration file error near: 234"

### ISSUE THREAD

**Issue by dbeniamine** [soctrace-inria/framesoc#188]
Hi,

When I try to visualize Moca traces with Ocelotl, Framesoc crashes with the following error:

    fr.inria.soctrace.lib.model.utils.SoCTraceException: Color configuration file error near: 234,
	at fr.inria.soctrace.framesoc.ui.colors.FramesocColorManager.getFramesocColor(FramesocColorManager.java:368)
	at fr.inria.soctrace.framesoc.ui.colors.FramesocColorManager.loadFile(FramesocColorManager.java:330)
	at fr.inria.soctrace.framesoc.ui.colors.FramesocColorManager.<init>(FramesocColorManager.java:82)
	at fr.inria.soctrace.framesoc.ui.colors.FramesocColorManager.<clinit>(FramesocColorManager.java:74)
	at fr.inria.soctrace.tools.importer.utils.ColorManager.earlyStartup(ColorManager.java:40)
	at org.eclipse.ui.internal.EarlyStartupRunnable.runEarlyStartup(EarlyStartupRunnable.java:89)
	at org.eclipse.ui.internal.EarlyStartupRunnable.run(EarlyStartupRunnable.java:67)
	at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
	at org.eclipse.ui.internal.Workbench$56.run(Workbench.java:2755)
	at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)

The is the full trace: [moca_trace.txt](https://github.com/soctrace-inria/framesoc/files/113910/moca_trace.txt)

Bye,

David

**Comment by dosimont** [comment]
Hi. It seems to be a problem with the color management. Can you provide me with the file containing the event producers and event types colors (which is probably located in the Eclipse workspace)?

**Comment by ycorre** [comment]
I agree with Damien, it is probably a problem with the color management. The color configuration files are located in your Eclipse directory : /[$pathToEclipse]/configuration/fr.inria.soctrace.framesoc.ui/.

If you could upload the two files located in that directory, we could try to reproduce the bug.

Otherwise, a quick fix for you would be to delete both these files as they will be automatically regenerated at the next launch. However, you would lose any customisation you would have made on the colors.

**Comment by dbeniamine** [comment]
Sorry for the late reply, as I changed a few things in the Moca importer the bug stops occurring ...
I attach my current files (I added the .TXT extension so github accept the upload) and as suggested by Youenn I will remove them.

[event_producer_colors.txt](https://github.com/soctrace-inria/framesoc/files/119117/event_producer_colors.txt)
[event_type_colors.txt](https://github.com/soctrace-inria/framesoc/files/119118/event_type_colors.txt)

**Comment by dosimont** [comment]
I believe the issue is closed.
